"""Initial migration

Revision ID: 0932090a9269
Revises: 
Create Date: 2024-09-20 14:15:23.657082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0932090a9269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False))
    
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('posts', 'poster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'poster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
